<head>
<title>the aegis PHP nano web server official homepage</title>
</head>
<body bgcolor="#000000" text="#00CCCC" link="#00FFFF" vlink="#00FFFF" alink="#00FFFF">
<font face="Verdana" size="2">
<br>
<center><b><font size="5">aEGiS PHP nano web demo server</font></b></center>
<br><br>
<hr style="height:1px;" width="95%" color="#00CCCC">
<br><br><br>
<table width="95%" align="center"><tr><td>
<font face="Verdana" size="2">
<table width="95%" cellspacing="0" cellpadding="0" align="center">
<tr><td align="left"><font size="2" valign="top">
<br><br><br>

<center>
This page is served to you by aEGiS nanoweb<br>
<br>

<?="<img src=\"".$PHP_SELF."?=".php_logo_guid()."\"border=\"0\" alt=\"PHP Logo\">"?>

</center>

<br><br><br>


<center>
this is an example of simple dynamic content generated by php and served by nanoweb<br><br>

user agent<br>
<b>

<?

echo getenv("HTTP_USER_AGENT");

?>

</b><br><br>
php version<br>
<b>

<?

echo phpversion();

?>

</b><br><br>
mysql version<br>
<b>

<?

$cid=mysql_pconnect("localhost", "root");
$q=mysql_query("select version()");
$r=mysql_fetch_array($q);
mysql_free_result($q);
mysql_close($cid);
echo $r[0];

?>

</b><br><br>
system uptime<br>
<b>

<?

system("uptime");

?>

</b><br><br>


</center>

<br><br><br>
<center><a href="http://nanoweb.si.kz">back</a></center>
</td></tr>
</table>
<br><br><br>
</font>
</td></tr></table>
<br><br><br>
<hr style="height:1px;" width="95%" color="#00CCCC">
<br><br>
<center>
<font size="1">
This site and all its contents are (c)2002 by <a href="http://si.kz" target="_new">sIX</a><br><? echo date("d-M-Y H:i:s"); ?><br>
<a href="http://nanoweb.si.kz"><img src="poweredbynanoweb-black.gif" border="0"></a><br>
<br>
</center>
</font>
